package exception;

public class Main {
    public static void main(String[] args) throws UserDefinded {
        int a = 5;
        int b = 0;
        try{
            divide(a,b);
        }
        catch(Exception e){
            e.getMessage();
        }
        if(b==0){
            throw new UserDefinded("This is userdefined");//user defined exception...
        }


    }
    public static int divide(int a, int b){
        int divide = a / b;
        if(b==0)
            throw new ArithmeticException("cannot be divided by zero");
        return divide;
    }
}
